#!/bin/bash
FNAME=$1
URL=$2
touch "$FNAME.html"
CALL_STRING=$(python3 /Users/audunleganger/Programmering/scripts/osx/data_retriver.py $FNAME $URL)
CALL_STRING_HTML="$CALL_STRING --nohtml"
fe $CALL_STRING_HTML
hdc $CALL_STRING
code "$FNAME.html"